"""add goal_notes table

Revision ID: 6967de255b48
Revises: d1e2f3g4h5i6
Create Date: 2026-08-23 07:51:12.618763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6967de255b48'
down_revision: Union[str, None] = 'd1e2f3g4h5i6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goal_notes',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('goal_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('progress_at_time', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goal_notes_goal_id'), 'goal_notes', ['goal_id'], unique=False)
    op.create_index(op.f('ix_goal_notes_user_id'), 'goal_notes', ['user_id'], unique=False)
    op.create_table('goal_reviews',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('goal_id', sa.Uuid(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goal_reviews_goal_id'), 'goal_reviews', ['goal_id'], unique=False)
    op.create_index(op.f('ix_goal_reviews_user_id'), 'goal_reviews', ['user_id'], unique=False)
    op.create_foreign_key(None, 'habits', 'habit_chains', ['chain_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_tasks_priority'), 'tasks', ['priority'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_priority'), table_name='tasks')
    op.drop_constraint(None, 'habits', type_='foreignkey')
    op.drop_index(op.f('ix_goal_reviews_user_id'), table_name='goal_reviews')
    op.drop_index(op.f('ix_goal_reviews_goal_id'), table_name='goal_reviews')
    op.drop_table('goal_reviews')
    op.drop_index(op.f('ix_goal_notes_user_id'), table_name='goal_notes')
    op.drop_index(op.f('ix_goal_notes_goal_id'), table_name='goal_notes')
    op.drop_table('goal_notes')
    # ### end Alembic commands ###
