"""add journey models achievements progress_paths life_scores

Revision ID: cbb598ab9a55
Revises: h8i9j0k1l2m3
Create Date: 2026-08-22 10:07:32.773098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'cbb598ab9a55'
down_revision: Union[str, None] = 'h8i9j0k1l2m3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_blocks', 'content',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    op.create_index(op.f('ix_project_blocks_project_id'), 'project_blocks', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_blocks_user_id'), 'project_blocks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_blocks_user_id'), table_name='project_blocks')
    op.drop_index(op.f('ix_project_blocks_project_id'), table_name='project_blocks')
    op.alter_column('project_blocks', 'content',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    # ### end Alembic commands ###
